apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-29T10:06:25Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "5668"
  uid: 51fec500-69c3-45fb-bcaf-9141c85ffbf5
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.99.210.156
  clusterIPs:
  - 10.99.210.156
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32446
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}